name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 16
                cache: npm
            - run: npm ci
            - name: Build
              run: npm run build
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: dist/index.js
