# This is an example of how to use the bot to triage issues

name: Tribble
on:
  issues:
    types:
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: arctic-hen7/tribble-bot@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
